# ==============================================================
#MySQL connection 
# ==============================================================

import os
from sqlalchemy import create_engine, text
from dotenv import load_dotenv

load_dotenv()

# ==============================================================
# Engine 
# ==============================================================

_engine = None  

def get_engine():
    """
    Returns a singleton SQLAlchemy engine.
    Created once and reused across all queries.
    """
    global _engine
    if _engine is None:
        user     = os.getenv("MYSQL_USER")
        password = os.getenv("MYSQL_PASSWORD")
        host     = os.getenv("MYSQL_HOST", "localhost")
        port     = os.getenv("MYSQL_PORT", "3306")
        db       = os.getenv("MYSQL_DB")

        connection_string = f"mysql+pymysql://{user}:{password}@{host}:{port}/{db}"
        _engine = create_engine(
            connection_string,
            pool_pre_ping=True,   
            pool_recycle=3600     
        )
    return _engine


# ==============================================================
# Safety Guard — only SELECT allowed
# ==============================================================


_FORBIDDEN_KEYWORDS = {
    "drop", "delete", "update", "insert",
    "alter", "truncate", "replace", "create",
    "grant", "revoke", "exec", "execute"
}

def is_safe_query(query: str) -> bool:    
    """
    Validates that the query is a read-only SELECT.
    Blocks any mutation or destructive SQL.
    Returns True if safe, False otherwise.
    """
    cleaned = query.strip().lower()


    if not cleaned.startswith("select"):
        return False


    for word in _FORBIDDEN_KEYWORDS:
        if word in cleaned:
            return False
      
    return True


# ==============================================================
# Query Executor
# ==============================================================

def run_query(query: str) -> list[dict] | str:  
    """
    Safely executes a SQL SELECT query.

    Args:
        query (str): SQL query — generated by the LLM agent.

    Returns:
        list[dict]: Rows as list of dictionaries if successful.
        str: Error/warning message if blocked or failed.

    Example:
        run_query("SELECT name, department FROM employees WHERE department = 'HR'")
        → [{"name": "Ahmed", "department": "HR"}, ...]
    """

   
    if not is_safe_query(query):
        return "❌ Query blocked: only SELECT statements are allowed. No data was modified."


    try:
        engine = get_engine()
        with engine.connect() as conn:   
            result = conn.execute(text(query)) 
            rows = [dict(row._mapping) for row in result] 


        if not rows:
            return "⚠️ Query executed successfully but returned no results."

        return rows

    except Exception as e:
        return f"❌ SQL Error: {str(e)}"