# ==============================================================
# MySQL connection + safe query execution
# ==============================================================

import os
from sqlalchemy import create_engine, text
from dotenv import load_dotenv

load_dotenv()

# ==============================================================
# Engine 
# ==============================================================

_engine = None

def get_engine():
    """
    Returns a singleton SQLAlchemy engine.
    Created once and reused across all queries.

    Two modes:
      - Local  → MYSQL_SSL=false (default) — no SSL
      - Cloud  → MYSQL_SSL=true            — SSL required (Aiven)
    """
    global _engine
    if _engine is None:
        user     = os.getenv("MYSQL_USER")
        password = os.getenv("MYSQL_PASSWORD")
        host     = os.getenv("MYSQL_HOST", "localhost")
        port     = os.getenv("MYSQL_PORT", "3306")
        db       = os.getenv("MYSQL_DB")

        connection_string = (
            f"mysql+pymysql://{user}:{password}@{host}:{port}/{db}"
        )

        
        ssl_required = os.getenv("MYSQL_SSL", "false").lower() == "true"

        if ssl_required:
            
            print(f"☁️ MySQL Cloud mode — SSL enabled → {host}:{port}/{db}")
            _engine = create_engine(
                connection_string,
                connect_args={
                    "ssl": {"ssl_mode": "REQUIRED"}
                },
                pool_pre_ping=True,    
                pool_recycle=3600      
            )
        else:
            # 🖥️ Local mode — no SSL needed
            print(f"🖥️ MySQL Local mode → {host}:{port}/{db}")
            _engine = create_engine(
                connection_string,
                pool_pre_ping=True,    
                pool_recycle=3600     
            )

    return _engine


# ==============================================================
# Safety Guard 
# ==============================================================


_FORBIDDEN_KEYWORDS = {
    "drop", "delete", "update", "insert",
    "alter", "truncate", "replace", "create",
    "grant", "revoke", "exec", "execute"
}

def is_safe_query(query: str) -> bool:
    """
    Validates that the query is a read-only SELECT.
    Blocks any mutation or destructive SQL.
    Returns True if safe, False otherwise.

    Examples:
        is_safe_query("SELECT * FROM employees") → True
        is_safe_query("DROP TABLE employees")    → False
        is_safe_query("DELETE FROM employees")   → False
    """
    cleaned = query.strip().lower()

    
    if not cleaned.startswith("select"):
        return False

    
    for word in _FORBIDDEN_KEYWORDS:
        if word in cleaned:
            return False

    return True


# ==============================================================
# Query Executor
# ==============================================================

def run_query(query: str) -> list[dict] | str:
    """
    Safely executes a SQL SELECT query.

    Args:
        query (str): SQL query — generated by the LLM agent.

    Returns:
        list[dict]: Rows as list of dictionaries if successful.
        str: Error/warning message if blocked or failed.

    Examples:
        run_query("SELECT full_name, department_id FROM employees LIMIT 5")
        → [{"full_name": "Ahmed", "department_id": 1}, ...]

        run_query("DROP TABLE employees")
        → "❌ Query blocked: only SELECT statements are allowed."
    """
    
    if not is_safe_query(query):
        return "❌ Query blocked: only SELECT statements are allowed. No data was modified."

    
    try:
        engine = get_engine()
        with engine.connect() as conn:
            result = conn.execute(text(query))
            
            
            rows = [dict(row._mapping) for row in result]

        
        if not rows:
            return "⚠️ Query executed successfully but returned no results."

        return rows

    except Exception as e:
        return f"❌ SQL Error: {str(e)}"