# MCP Server connections
# ==============================================================
# mcp_tools.py — MCP Server Tool Registry
# ==============================================================

import os
from typing import Any
from dotenv import load_dotenv

from src.db.vector_store import get_query_engine
from src.db.sql_client import run_query

load_dotenv()

# ==============================================================
# Internal LLM helpers 
# ==============================================================

from openai import OpenAI as _OpenAI

_openai_client = _OpenAI(api_key=os.getenv("OPENAI_API_KEY"))
OPENAI_MODEL    = os.getenv("OPENAI_MODEL", "gpt-4o")
OLLAMA_BASE_URL = os.getenv("OLLAMA_BASE_URL", "http://localhost:11434")
OLLAMA_MODEL    = os.getenv("OLLAMA_MODEL", "llama3")


# ==============================================================
# Tool: search_docs
# ==============================================================

def search_docs(query: str, top_k: int = 4) -> dict[str, Any]:   
    """
    MCP Tool — Search company documents via Qdrant RAG.

    Args:
        query  (str): Natural language question (Arabic or English).
        top_k  (int): Number of document chunks to retrieve (default 4).

    Returns:
        dict with keys:
            - answer       (str)       : Synthesized answer from documents
            - source_texts (list[str]) : Raw text of retrieved chunks
            - scores       (list[float]): Similarity scores per chunk
            - success      (bool)      : False if an error occurred

    Usage (from nodes.py):
        result = search_docs("What is the remote work policy?")
        print(result["answer"])
    """
    try:
        engine   = get_query_engine(top_k=top_k)
        response = engine.query(query)

        
        try:
            nodes        = response.source_nodes   
            source_texts = [n.node.text for n in nodes]   
            scores       = [float(n.score) if n.score else 0.0 for n in nodes]
        except Exception:
            source_texts = []
            scores       = []

        return {
            "answer":       str(response),
            "source_texts": source_texts,
            "scores":       scores,
            "success":      True,
        }

    except Exception as e:
        return {
            "answer":       f"❌ Document search failed: {str(e)}",
            "source_texts": [],
            "scores":       [],
            "success":      False,
        }


# ==============================================================
# Tool: query_database
# ==============================================================

def query_database(sql: str) -> dict[str, Any]:
    """
    MCP Tool — Execute a read-only SQL query on MySQL.

    Safety: run_query() blocks non-SELECT statements before execution.

    Args:
        sql (str): A SELECT SQL query (generated by an LLM or hardcoded).

    Returns:
        dict with keys:
            - rows    (list[dict] | str): Rows as dicts, or error/warning string
            - count   (int)             : Number of rows returned (0 on error)
            - success (bool)            : False if blocked or errored
            - sql     (str)             : The query that was run (for logging)

    Usage:
        result = query_database("SELECT full_name, salary FROM employees LIMIT 5")
        for row in result["rows"]:
            print(row)
    """
    result = run_query(sql)

    if isinstance(result, str):  
        
        return {
            "rows":    result,
            "count":   0,
            "success": False,
            "sql":     sql,
        }

    return {
        "rows":    result,
        "count":   len(result),
        "success": True,
        "sql":     sql,
    }


# ==============================================================
# Tool: ask_public_llm
# ==============================================================

def ask_public_llm(
    system_prompt: str,
    user_message:  str,
    temperature:   float = 0.1
) -> dict[str, Any]:
    """
    MCP Tool — Send a prompt to GPT-4o (OpenAI cloud).

    Use for: routing decisions, SQL generation, general answers.
    Do NOT use for sensitive data — use ask_private_llm instead.

    Args:
        system_prompt (str)  : Instruction context for the model.
        user_message  (str)  : The actual user question or task.
        temperature   (float): 0.0–1.0, lower = more deterministic (default 0.1).

    Returns:
        dict with keys:
            - response (str)  : The model's text reply
            - model    (str)  : Model name used
            - success  (bool) : False if API call failed
    """
    try:
        resp = _openai_client.chat.completions.create(
            model=OPENAI_MODEL,
            messages=[
                {"role": "system", "content": system_prompt},
                {"role": "user",   "content": user_message},
            ],
            temperature=temperature,
        )
        return {
            "response": resp.choices[0].message.content.strip(),
            "model":    OPENAI_MODEL,
            "success":  True,
        }
    except Exception as e:
        return {
            "response": f"❌ GPT-4o call failed: {str(e)}",
            "model":    OPENAI_MODEL,
            "success":  False,
        }


# ==============================================================
# Tool: ask_private_llm
# ==============================================================

def ask_private_llm(
    system_prompt: str,
    user_message:  str,
    temperature:   float = 0.1
) -> dict[str, Any]:
    """
    MCP Tool — Send a prompt to a local Ollama model.

    Use ONLY for sensitive queries (salary, national ID, customer data).
    Data never leaves the machine.

    Requires:
        - `ollama serve` running in the background
        - Model pulled: `ollama pull llama3`

    Args:
        system_prompt (str)  : Instruction context for the model.
        user_message  (str)  : The actual user question or task.
        temperature   (float): 0.0–1.0, lower = more deterministic (default 0.1).

    Returns:
        dict with keys:
            - response (str)  : The model's text reply
            - model    (str)  : "ollama:<model_name>"
            - success  (bool) : False if Ollama call failed
    """
    try:
        client = _OpenAI(
            base_url=f"{OLLAMA_BASE_URL}/v1",
            api_key="ollama",  
        )
        resp = client.chat.completions.create(
            model=OLLAMA_MODEL,
            messages=[
                {"role": "system", "content": system_prompt},
                {"role": "user",   "content": user_message},
            ],
            temperature=temperature,
        )
        return {
            "response": resp.choices[0].message.content.strip(),
            "model":    f"ollama:{OLLAMA_MODEL}",
            "success":  True,
        }
    except Exception as e:
        return {
            "response": f"❌ Ollama call failed: {str(e)}",
            "model":    f"ollama:{OLLAMA_MODEL}",
            "success":  False,
        }


# ==============================================================
# Tool: get_employee_info
# ==============================================================

def get_employee_info(  
    name:       str | None = None,
    department: str | None = None,
    fields:     list[str] | None = None,
    limit:      int = 10,
) -> dict[str, Any]:
    """
    MCP Tool — Convenience wrapper for common employee lookups.

    Builds a safe SELECT query from parameters — no LLM needed for
    simple, predictable lookups (avoids LLM hallucinating column names).

    Args:
        name       (str | None)       : Employee name (partial match, LIKE).
        department (str | None)       : Department name (partial match, LIKE).
        fields     (list[str] | None) : Columns to return. Defaults to safe set.
        limit      (int)              : Max rows (default 10).

    Returns:
        Same shape as query_database() — rows, count, success, sql.

    Examples:
        get_employee_info(name="Ahmed")
        get_employee_info(department="IT", fields=["full_name", "position"])
        get_employee_info(department="HR", fields=["full_name", "email", "hiring_date"])
    """
    
    safe_default_fields = ["employee_id", "full_name", "email", "position", "department_id"]
    selected_fields     = fields if fields else safe_default_fields     

   
    allowed_columns = {
        "employee_id", "full_name", "age", "email",
        "address", "department_id", "position",
        "salary", "hiring_date", "marital_status", "gender"  
    }
    validated_fields = [f for f in selected_fields if f in allowed_columns]
    if not validated_fields:
        validated_fields = safe_default_fields

    columns = ", ".join(validated_fields)
    conditions: list[str] = []

    if name:
       
        safe_name = name.replace("'", "''")  # basic escape
        conditions.append(f"full_name LIKE '%{safe_name}%'")   # full_name matches your real column name

    if department:
        safe_dept = department.replace("'", "''")
        
        conditions.append(f"department_id IN (SELECT department_id FROM departments WHERE department_name LIKE '%{safe_dept}%')")

    where_clause = f"WHERE {' AND '.join(conditions)}" if conditions else ""
    sql = f"SELECT {columns} FROM employees {where_clause} LIMIT {limit}".strip()  # Removes extra spaces.

    return query_database(sql)


# ==============================================================
# Tool: get_schema_info
# ==============================================================

def get_schema_info() -> dict[str, Any]:
    """
    MCP Tool — Returns the HR database schema as a formatted string.

    Used to inject schema context into LLM prompts so the model knows
    what tables and columns exist before generating SQL.

    Returns:
        dict with keys:
            - schema  (str)  : Human-readable schema description
            - success (bool) : Always True (static data)
    """
    schema = """
HR Database Schema (MySQL):

Table: employees
  - employee_id    INT          Primary key
  - full_name      VARCHAR      Full name (Arabic or English)
  - age            INT          Employee age
  - email          VARCHAR      Work email (SENSITIVE)
  - password       VARCHAR      Hashed password (SENSITIVE)
  - address        VARCHAR      Home address (SENSITIVE)
  - department_id  INT          FK → departments.department_id
  - position       VARCHAR      Job title
  - salary         DECIMAL      Monthly salary (SENSITIVE)
  - hiring_date    DATE         Date joined
  - marital_status ENUM         'Single' | 'Married' (SENSITIVE)
  - gender         ENUM         'Male' | 'Female'

Table: departments
  - department_id    INT     Primary key
  - department_name  VARCHAR Department name
  - location         VARCHAR Office location

Table: products
  - product_id       INT          Primary key
  - product_name     VARCHAR      Product name
  - manufacture_year YEAR         Year manufactured
  - color            VARCHAR      Product color
  - cost             DECIMAL      Cost price
  - price            DECIMAL      Selling price

Table: cities
  - city_id    INT     Primary key
  - city_name  VARCHAR City name

Table: sales
  - sale_id      INT          Primary key
  - product_id   INT          FK → products.product_id
  - city_id      INT          FK → cities.city_id
  - quantity     INT          Units sold
  - sale_date    DATE         Date of sale
  - total_amount DECIMAL      Total sale value
""".strip()

    return {"schema": schema, "success": True}


# ==============================================================
# Tool Registry — all tools in one dict for easy discovery
# ==============================================================

TOOL_REGISTRY: dict[str, callable] = {  
    "search_docs":       search_docs,
    "query_database":    query_database,
    "ask_public_llm":    ask_public_llm,
    "ask_private_llm":   ask_private_llm,
    "get_employee_info": get_employee_info,
    "get_schema_info":   get_schema_info,
}


def call_tool(name: str, **kwargs) -> dict[str, Any]:
    """
    Unified entry point to call any registered MCP tool by name.

    Args:
        name   (str): Tool name — must be a key in TOOL_REGISTRY.
        **kwargs    : Arguments forwarded to the tool function.

    Returns:
        dict: Tool result. Always contains at least {"success": bool}.

    Raises:
        ValueError: If tool name is not in the registry.

    Usage:
        result = call_tool("search_docs", query="leave policy", top_k=3)
        result = call_tool("ask_public_llm",
                           system_prompt="You are an HR assistant.",
                           user_message="How many vacation days do I get?")
    """
    if name not in TOOL_REGISTRY:
        available = list(TOOL_REGISTRY.keys())
        raise ValueError(f"Unknown tool '{name}'. Available tools: {available}")

    print(f"🔧 MCP tool called: {name}")
    return TOOL_REGISTRY[name](**kwargs)